
# Environment file for calimflow

# run:
#   conda env create -f environment.yaml
#   conda activate calimflow
  

name: calimflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pip
  - pip:
    - -e .  
    - pytest>=7.0
    - pytest-cov
    - black
    - isort
    - mypy 